name: Smoke Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build distro
        run: mvn --batch-mode --update-snapshots clean package -DskipTests -pl dist -am
      - name: Start distro
        run: nohup ./dist/target/zeebe-broker/bin/broker > broker.log 3>&1 &; echo $! > broker_pid.txt
      - name: Check status
        run: ./dist/target/zeebe-broker/bin/zbctl --insecure status
